# Test against thsi version
environment:
  matrix:
    # node.js
    - nodejs_version : "8"

#Install scripts
install:
  -ps : Install-Product node $env:nodejs_version
  - npm install

#post-install test scripts
test_script:
    - node --version

    - npm test

build:off
